### ISSUE TITLE
🐛 [BUG] objc[23337]: Class AMSupportURLConnectionDelegate

### ISSUE THREAD

**Issue by solrevdev** [mas-cli/mas#304] opened 2020-09-24 11:44 UTC
## Your Environment

- `mas version`: 1.7.1
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 
```bash
system_profiler SPSoftwareDataType -detailLevel mini
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G6020)
      Kernel Version: Darwin 18.7.0
      Time since boot: 1 day 1:32
```

### mas Install Method

- [X] `brew install mas` (homebrew-core)

## Describe the Bug

Running any mas command gives this error message 

```bash
▲ (macmini.local) ~ mas version
objc[23337]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11199fc58) and /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x111802358). One of the two will be used. Which one is undefined.
1.7.1
▲ (macmini.local) ~ mas list
objc[24080]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x117bf9c58) and /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x117a5c358). One of the two will be used. Which one is undefined.
```

**Comment by dtgriscom** [comment] 2020-09-30 19:51
Confirmed on macOS 10.14.6:

````
DTG-MBPE-2:~ griscom$ mas list
objc[78064]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x112cf9c58) and /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x112b5c358). One of the two will be used. Which one is undefined.
````

**Comment by chris-araman** [comment] 2021-05-08 18:15
@dtgriscom, @solrevdev, do you still see this issue with mas 1.8.2?

**Comment by dtgriscom** [comment] 2021-05-08 19:37
I just tried with the existing version, and it now seems to work:

<pre>
DTG-MBPE-2:~ griscom$ mas version
1.7.1
DTG-MBPE-2:~ griscom$ 
</pre>
I have no idea what might have changed.

BTW, I tried upgrading mas using brew, and it failed:

<pre>
DTG-MBPE-2:~ griscom$ brew upgrade mas
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae

[... snip ...]

==> Upgrading 1 outdated package:
mas 1.7.1 -> 1.8.2
==> Upgrading mas 1.7.1 -> 1.8.2 
mas: A full installation of Xcode.app 12.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 12.0 cannot be installed on macOS 10.14.
You must upgrade your version of macOS.
Error: mas: An unsatisfied requirement failed this build.
DTG-MBPE-2:~ griscom$ mas version
1.7.1
DTG-MBPE-2:~ griscom$ 
</pre>

Let me know if there's something else you'd like me to try.

**Comment by chris-araman** [comment] 2021-05-08 21:11
@dtgriscom, thanks for checking!

Users of older macOS releases need to use the [custom Homebrew tap](https://github.com/mas-cli/mas#%EF%B8%8F-older-macos-versions).

**Comment by dtgriscom** [comment] 2021-05-08 21:18
Tried; 403 error.

<pre>
DTG-MBPE-2:~ griscom$ brew install mas-cli/tap/mas
==> Installing mas from mas-cli/tap
==> Downloading https://dl.bintray.com/phatblat/mas-bottles/mas-1.8.1.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "mas"
Download failed: https://dl.bintray.com/phatblat/mas-bottles/mas-1.8.1.mojave.bottle.tar.gz
DTG-MBPE-2:~ griscom$ 
</pre>

**Comment by chris-araman** [comment] 2021-05-08 21:37
Unfortunate timing.
https://github.com/mas-cli/homebrew-tap/issues/22

**Comment by dtgriscom** [comment] 2021-05-08 21:39
Happy to try again; let me know when.

**Comment by chris-araman** [comment] 2021-05-09 00:40
@dtgriscom, the custom tap should be fixed now. Please try again with 1.8.2 and let us know.

**Comment by dtgriscom** [comment] 2021-05-09 00:42
Worked, but had some warnings:

<pre>
DTG-MBPE-2:~ griscom$ brew upgrade mas-cli/tap/mas
==> Upgrading 1 outdated package:
mas-cli/tap/mas 1.7.1 -> 1.8.2
==> Upgrading mas-cli/tap/mas 1.7.1 -> 1.8.2 
==> Downloading https://github.com/mas-cli/mas/releases/download/v1.8.2/mas-1.8.2.mojave.bottle.tar.gz
Already downloaded: /Users/griscom/Library/Caches/Homebrew/downloads/cef992795310cf5527c68c7b5d4ea5899f75a35470004ad6077a642a6e3d6590--mas-1.8.2.mojave.bottle.tar.gz
==> Pouring mas-1.8.2.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/mas/1.8.2: 7 files, 1.5MB
Removing: /usr/local/Cellar/mas/1.7.1... (31 files, 10.9MB)
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the mikhailai/misc tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/mikhailai/homebrew-misc/usbutils.rb:12

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the mikhailai/misc tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/mikhailai/homebrew-misc/usbutils.rb:13

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the mikhailai/misc tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/mikhailai/homebrew-misc/usbutils.rb:14

DTG-MBPE-2:~ griscom$ mas version
1.8.2
DTG-MBPE-2:~ griscom$ 
</pre>

**Comment by chris-araman** [comment] 2021-05-09 01:11
@dtgriscom, thanks for the report. It looks like those warnings were from the 1.7.1 formula, which have since been [fixed](https://github.com/mas-cli/homebrew-tap/commit/f57c0447c7cc0fa686041395b19b5900c7f8d56f#diff-ad35e3230174c9d621ebb7ac971b7582222b4b99367542b858d91b5ef5c27d0cL13).

**Closed by chris-araman** 2021-05-09 01:11 UTC
Labels: 🐛 bug, 🗣 awaiting reporter reply
