### ISSUE TITLE
🐛 [BUG] Messenger reports "upgrade" to lower version; always appears outdated

### ISSUE THREAD

**Issue by sjml** [mas-cli/mas#331] opened 2021-03-20 14:17 UTC
## Your Environment

- `mas version`: 1.8.1
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.15.7

### mas Install Method

- ☑️ `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 10.?

## Describe the Bug

When running `mas upgrade` to upgrade Messenger (1480068668), it still shows up in the `outdated` list. It seems to be a problem that it's reporting an "upgrade" needed to a lower version number? 

## To Reproduce

1. Run `mas outdated` to see Messenger in need of upgrade. 
2. Run `mas upgrade` to update it. 
3. Note that it still appears when `mas outdated` is run again.

(Terminal log below)

## Expected Behavior

A recently upgraded program will no longer be listed as outdated. 

## Actual Behavior

Messenger seems to always be in need of an upgrade. 

## Screenshots, Terminal Output

```
% mas outdated
1480068668 Messenger (95.7.118 -> 92.0)
% mas upgrade
Upgrading 1 outdated application:
Messenger (95.7.118)
==> Downloading Messenger
==> Installed Messenger
% mas outdated
1480068668 Messenger (95.7.118 -> 92.0)
```

The installed version of Messenger does report itself as 95.7.118.

**Comment by chris-araman** [comment] 2021-03-21 01:23
The bundle version does not match the App Store version.
```
<key>CFBundleShortVersionString</key><string>95.7.118</string>
```

This seems to be a regression from https://github.com/mas-cli/mas/pull/312.

**Comment by GentleHoneyLover** [comment] 2021-03-21 16:55
Exactly the same issue here. 

macOS version 11.2.3 (20D21)
mas version 1.8.1

`% mas outdated
1477857867 DevSwatch (1.3 -> 1.1)
1510445899 Meeter (1.9.3 -> 1.1.3)`

Both of these apps are already at their latest versions. But mas keeps upgrading them.

**Comment by lonelykid** [comment] 2021-03-22 03:13
There have been several related issues. https://github.com/mas-cli/mas/issues/290 
Your problem seems a little different. `mas info` and `mas outdated` reported v92.0. appstore also shows v92.0 But the version installed is 95.7.118. https://github.com/mas-cli/mas/pull/312 didn't do anything wrong here. It's appstore.

**Comment by sjml** [comment] 2021-03-22 07:49
I wonder if mas should be reporting "outdated" if the installed version is **higher** than the reported version from the App Store. Understanding that there's not much that can be done on the tool side to make sure the App Store metadata matches the app's plist, maybe it could at least assume that version numbers increase over time rather than decrease.

**Comment by alexbarton** [comment] 2021-04-03 14:08
I’m seeing this as well – but only `mas` shows those apps as _outdated_ and tries to „upgrade“ it over and over again; not the App Store application itself. So the App Store app uses an different logic to detect „outdated“ apps?

```bash
❯ mas outdated
1225393668 Code Reader (5.12.3 -> 5.12.2)
1481669779 Evernote Web Clipper (1.0.11 -> 7.13.6)
1480068668 Messenger (95.7.118 -> 92.0)
```

**Comment by RickyRomero** [comment] 2021-04-07 17:39
```zsh
r@burnout ~ % mas outdated
1015043880 Shut Up (3.1 -> 1.10)
```

I have a universal app on the App Store which has different versions available on iOS and macOS. Both versions share a bundle ID - `com.rickyromero.shutup` but are currently based on different source trees. The latest macOS version is 3.1, and the latest iOS version is 1.10.

Perhaps this explains the strange behavior?

**Comment by chris-araman** [comment] 2021-04-27 04:51
The issue with `Messenger` for macOS should be resolved by #346. The absence of iOS apps is tracked in #321.

> I have a universal app on the App Store which has different versions available on iOS and macOS. Both versions share a bundle ID - `com.rickyromero.shutup` but are currently based on different source trees. The latest macOS version is 3.1, and the latest iOS version is 1.10.

@RickyRomero, would you be willing to open a new issue with details on this?

**Closed by chris-araman** 2021-04-27 04:51 UTC
Labels: 🐛 bug

**Comment by jaklan** [comment] 2021-05-06 03:35
@chris-araman where can we expect the release incl. that fix? Or maybe any pre-release?

**Comment by chris-araman** [comment] 2021-05-06 05:24
@jaklan, I'm not sure what @phatblat has in mind. AFAIK, the [migration](https://github.com/mas-cli/homebrew-tap/issues/19) from Bintray to GitHub Packages might be the only thing blocking release, but I think that only blocks release to the [Homebrew tap](https://github.com/mas-cli/homebrew-tap) for macOS 10.11 through 10.14.

@phatblat, would it be possible to get a release out sooner, without waiting for that migration?

**Comment by phatblat** [comment] 2021-05-07 02:57
The homebrew formula update is the first tricky part. The last couple releases I've tagged and somebody started updating the formula before I could get to it. That's fine when only a version bump is needed, but we changed the formula a bit with the removal of carthage.

I'll start rolling out 1.8.2 now.

**Comment by phatblat** [comment] 2021-05-07 03:46
The [1.8.2 release](https://github.com/mas-cli/mas/releases/tag/v1.8.2) is up and has a .pkg installer attached. Homebrew is going to take a little longer as I hit a snag updating the formula #363

**Comment by chris-araman** [comment] 2021-05-07 03:47
Thanks, @phatblat!
