### ISSUE TITLE
macOS ventura: Redownload Unavailable with This Apple ID

### ISSUE THREAD

**Issue by paulz** [mas-cli/mas#488] opened 2023-04-06 03:42 UTC
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): macOS 13.3 (22E252)

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

`mas lucky seashore` results in 

```
No downloads
Error: No downloads began
```

and AppStore alert, see screenshot below

## To Reproduce

1. Login to AppStore
1. Download Seashore app
1. Delete /Applications/Seashore.app
1. run `mas lucky seashore`
2. see error

## Expected Behavior

Successful download

## Actual Behavior

Error and Alert

## Screenshots, Terminal Output

![image](https://user-images.githubusercontent.com/59230/230265835-04d1e144-1e71-4623-a055-7eed67937a97.png)

```bash
$ mas lucky seashore
No downloads
Error: No downloads began
```

## Additional Context

> This redownload is not available for this Apple ID either because it was bought by a different user or the item was refunded or cancelled.

Used to work in macOS Monterey macOS 12.6

Installing app by ID works:
```
mas install 1448648921                               
==> Downloading Seashore
==> Installed Seashore
```

and subsequent attempts produce correct warning:
```
mas install 1448648921
Warning: Seashore is already installed
```

**Comment by scientificworld** [comment] 2023-10-13 12:03
Also met this on macOS Monterey 12.7.

**Comment by geekobiloba** [comment] 2023-12-17 01:34
Any update on this bug?

**Comment by rgoldberg** [comment] 2024-09-05 10:14
`mas lucky <term>` installs the first result from the Mac App Store from `mas search <term>`.

The first result for `mas search seashore` is `897446215  Canva: Design, Art & AI Editor`, which is not `1448648921  Seashore`.

```
$ mas search seashore
   897446215  Canva: Design, Art & AI Editor              (4.126.0)
   944665061  ProKnockOut-Cut Paste Photos                (7.39)
  1448648921  Seashore                                    (3.37)
…
```

You're dealing with 2 different apps here.

Can we close this?

**Comment by rgoldberg** [comment] 2024-09-14 03:48
@paulz `mas install 1448648921` is always working for you, right?

`mas lucky <term>` installs the first result from the Mac App Store from `mas search <term>`.

The first result for `mas search seashore` is `897446215  Canva: Design, Art & AI Editor`, which is not `1448648921 Seashore`.

```
$ mas search seashore
   897446215  Canva: Design, Art & AI Editor              (4.126.0)
   944665061  ProKnockOut-Cut Paste Photos                (7.39)
  1448648921  Seashore                                    (3.37)
…
```

What happens if you run `mas install 897446215`? That will help us determine if the problem is with `mas lucky` or with installing `897446215` from any mas command.

**Comment by rgoldberg** [comment] 2024-10-26 07:09
`mas install` is poorly named. It can only install apps that have been previously "purchased" or "gotten" by your Apple ID. To be in that situation, you must either have never installed the app on your current machine, or you must have uninstalled the app from your current machine.

`mas purchase` is also poorly named. It will "get" (aka "purchase") free apps that you haven't yet "gotten" / "purchased" with your Apple ID. It does not yet work with non-free apps.

The messaging in the dialog is cryptic since it's from Apple, which doesn't expect the circumstances from this issue.

Will close this issue because this is known behavior, and because there are numerous mas issues regarding fixing various aspects of this issue. See:

- #557
- #558
- #218
- #146

**Closed by rgoldberg** 2024-10-26 07:09 UTC
Labels: 🐛 bug, 🗣 awaiting user reply
