### ISSUE TITLE
[FR] support JSON output

### ISSUE THREAD

**Issue by andrewcrook** [mas-cli/mas#457] opened 2022-03-13 11:45 UTC
**Is your feature request related to a problem? Please describe.**
easier than parsing may allow use with other tools

**Describe the solution you'd like**
output JSON when `--json ` or `-j`  is used
example
`mas list --json `

**Describe alternatives you've considered**
scripting

**Comment by n8felton** [comment] 2022-04-28 19:18
Duplicate of #190

**Comment by rgoldberg** [comment] 2024-09-11 23:36
Closing as a duplicate of #190 (please follow that issue).

If you think this issue is different than #190, please let us know.

**Closed by rgoldberg** 2024-09-11 23:36 UTC
Labels: 🆕 feature request
