### ISSUE TITLE
Reports an update for NordVPN when there is none

### ISSUE THREAD

**Issue by StrangeRanger** [mas-cli/mas#466] opened 2022-05-25 17:17 UTC
## Your Environment

`mas version`: macOS 12.4

### mas Install Method

`brew install mas` (homebrew-core)

## Describe the Bug

When using `mas outdated`, it says NordVPN has a 7.12.0 update, when the App store says nothing about the update. When trying to update, mas does it's thing, but when NordVPN is relaunched, it's the same version is was previously. One thing to note, is that an application called CleanMyMac reports and does the same thing.
NordVPN has a version for iOS with the latest release of 7.12.0. When checking out what the App Store id is for both the macOS and iOS version of the app, it appears they both have the same id, being "905953485". Is it possible that mas doesn't differentiate between the iOS version number and the macOS version number?

## To Reproduce

1. Have NordVPN installed on macOS (version downloaded from the App Store).
2. Enter into the terminal `mas outdated` and see it say that a new version of NordVPN (version 7.12.0) is available.
3. Take a look at the App Store and see that it says the latest version is 7.6.0.
4. If you want, try to update NordVPN using `mas upgrade`, and see that once relaunched, NordVPN was not updated.

## Expected Behavior

Reports, correctly, whether or not an application has an update for it's respective OS.

## Actual Behavior

Reports an update that doesn't exist, or possibly belongs to a different OS.

**Comment by nicerloop** [comment] 2022-06-28 14:44
See https://github.com/mas-cli/mas/issues/468

`{
  "platform": "osx",
  "version": "7.6.0"
}
{
  "platform": "ios",
  "version": "7.14.0"
}`

**Comment by rgoldberg** [comment] 2024-09-14 11:48
Closing as a duplicate of #491. PR #496 fixed the issue. It will be released in the upcoming version 1.8.7, which is currently in beta.

If you think this issue is different than #491, please let us know.

**Closed by rgoldberg** 2024-09-14 11:48 UTC
Labels: 🐛 bug
