### ISSUE TITLE
`search` outputs no results

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#182] opened 2018-10-25 05:53 UTC
I have the latest version of mas installed via Homebrew.  I am on macOS Mojave 10.14. When I try to search for an item in the Mac App Store, I get no results at all, I just get a new command prompt.  I am currently signed into the MAS from GUI.

I've tried searching for various items, such as Amphetamine, Lightshot, etc. I've also tried with the --price flag, and the results are the same, I get a new command prompt.

Example:
```
~ $ mas version
1.4.3
~ $ mas search Xcode
~ $
```

**Comment by fdrouet** [comment] 2018-10-25 08:29
Same problem with macOS High Sierra

```
~ $ mas version
1.4.3
~ $ mas search Xcode
~ $
```

**Comment by JavierCane** [comment] 2018-10-25 16:15
Same here also with MacOS Mojave 10.14 (18A391). Just in case it's useful, it doesn't seem to be related with the latest issues regarding sign in from the MAS GUI since I can actually install the packages:

```bash
~ mas version
1.4.3
~ mas list
540348655 Monosnap (3.5.2)
926707738 Countdowns (1.3.2)
587512244 Kaleidoscope (2.2.2)
408981434 iMovie (10.1.9)
715464874 Disk Map (2.3)
409183694 Keynote (8.2)
1278508951 Trello (2.10.7)
441258766 Magnet (2.4)
~ mas search imovie
~ mas search tweetbot
~ mas search numbers
~ mas install 409203825
==> Downloading Numbers
==> Installed Numbers
```

**Comment by phatblat** [comment] 2018-10-26 03:02
Weird. Looks like this broke in 1.4.3. Thanks for the info!

**Comment by SheldonWangRJT** [comment] 2018-11-01 21:01
I am running `$mas search Xcode` on High Sierra(10.13.6), it is also returning no results.
The version of mas I am using is also 1.4.3 but 1.3.1 is also not working.

**Comment by SheldonWangRJT** [comment] 2018-11-01 21:02
I also tried to run `lucky`. It is throwing exceptions like:
```
$ mas lucky xcode
Could not cast value of type 'NSTaggedPointerString' (0x7fff894b35d8) to 'NSNumber' (0x7fff89920200).
```

**Comment by vimusr** [comment] 2018-11-09 19:56
I just upgraded to the lasted version of macOS, 10.14.1, and `mas search` now appears to be working.

```
~ $ sw_vers -productVersion
10.14.1
~ $ mas search amphetamine
   937984704  Amphetamine (4.0.4)
~ $
```

**Comment by vimusr** [comment] 2018-11-10 05:36
@Henrietta1989 I'm not sure how eventsripts not being found is related to this problem. From what I can tell, the search function works properly with 10.14.1 and searches the Mac App Store for eventscripts--it just doesn't find any results.  Both mas and the MAS GUI won't find results for eventscripts, but that's not necessarily a problem with mas search.

**Comment by JavierCane** [comment] 2018-11-12 15:22
Confirmed. It seems to work on 10.14.1 (at least in my case 🙂)

```bash
~ sw_vers -productVersion
10.14.1
~ mas version
1.4.3
~ mas list
540348655 Monosnap (3.5.2)
926707738 Countdowns (1.3.2)
587512244 Kaleidoscope (2.2.2)
1091189122 Bear (1.6.6)
715464874 Disk Map (2.3)
408981434 iMovie (10.1.10)
409183694 Keynote (8.3)
784801555 Microsoft OneNote (16.18)
1278508951 Trello (2.10.8)
441258766 Magnet (2.4)
409203825 Numbers (5.3)
~ mas search imovie
   408981434  iMovie                                             (10.1.10)
   855724960  Lessons for iMovie                                 (2.2.4)
   733989909  Course for Intro to iMovie                         (2.0.2)
   416624070  Tutor for iMovie '11                               (1.32)
   495987485  MovieDrops HD for iMovie and for Final Cut Pro     (1.0)
   490427273  Clips FX for iMovie                                (2.1)
  1220986982  Edit8 Audio Sync Pro for iMovie-PP-FCPX            (1.0)
   645633897  Clips 3D for iMovie                                (2.3)
   772117255  Learn - iMovie 10 Edition                          (3.1.1)
   447474913  Course For iMovie '11 101 - Core iMovie '11        (1.1)
  1062355569  Tutor for iMovie                                   (10.4)
   982388492  Course For iMovie - Trimming, Titles, Transitions  (2.0.2)
   979389049  Story Telling and Editing Course For iMovie        (2.0.2)
   767533911  Tutorials for iMovie                               (1.2)
   717368886  NYC TimeLapse for iMovie and FCPX                  (1.0)
   735255637  Course For iMovie 101 - Getting Started With Your  (2.0.2)
   882923216  Course for Effects and Color Correction for iMovie (2.1.0)
  1064870190  Backups for iMovie                                 (1.0.1)
   944384899  Prep for iMovie for iOS                            (1.1)
~ mas search tweetbot
   557168941  Tweetbot 2 for Twitter (2.5.8)
  1384080005  Tweetbot 3 for Twitter (3.2)
  1227057295  TweetShot              (1.6.5)
  1383618774  TweetBar               (1.0)
```

Thanks!

**Comment by phatblat** [comment] 2018-11-13 02:40
Well, I'm shocked, but macOS 10.14.1 does appear to fix the search command!

```
$ mas search slack
   803453959  Slack                                              (3.3.3)
  1128645172  QuickPlan Slack Bot - Project Management team Comm (1.0)
  1293799461  Send It - For Slack                                (1.0)
  1271281910  Activebot for Slack                                (1.0)
   994537604  ChannelScrobbler - Real-time scrobble bot for Last (1.2)
  1406123151  Ratstash - For Slack                               (1.3.6)
$ mas install 803453959
==> Downloading Slack
############------------------------------------------------ 20.0% Downloading
```

I'm surprised because the search command doesn't use the MAS app APIs, but rather does a [web API](https://github.com/mas-cli/mas/blob/master/App/Commands/Search.swift#L76) call to iTunes. I'm guessing this was caused by some sort of back end issue that was resolved around the same time that 10.14.1 was rolled out.

**Comment by SheldonWangRJT** [comment] 2018-11-13 16:18
it is back working for me!

**Comment by phatblat** [comment] 2018-11-16 19:45
Can anyone still on macOS 10.14.0 confirm whether this is still an issue?

**Comment by phatblat** [comment] 2018-11-17 22:09
I tested mas 1.4.3 on macOS 10.14.0 and search is working again. Closing.

**Closed by phatblat** 2018-11-17 22:09 UTC
Labels: 🐛 bug
