### ISSUE TITLE
`search` negative app IDs

### ISSUE THREAD

**Issue by hao-lh** [mas-cli/mas#498] opened 2023-06-16 17:34 UTC
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 
      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      Time since boot: 1:30

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https:github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https:github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug
When use keyword with mas to search apps, some items returned with a negative MAS ID.

## To Reproduce

1. mas search xcode
2. some items from search results returned a negative ID
3. already highlighted details from below screenshot
4. should be type overflow 

## Screenshots, Terminal Output
<img width="547" alt="IMG_2023-06-16_12-09-04" src="https://github.com/mas-cli/mas/assets/14138581/5ded7d0a-a629-4a18-916a-68b958db9b80">

**Comment by bjesuiter** [comment] 2024-01-22 19:28
I have the same problem with "Lockera Widgets". 

`mas search "Lockera Widgets"` returns ` -2123114745  Lockera Widgets (1.6)`

and trying to install this with `mas "Lockera Widgets", id: -2123114745` fails.

**Comment by voodooGQ** [comment] 2024-02-03 19:59
Having the same issue with "iBar" showing up as ` -2146090692  iBar-Menubar icon control tool (1.2.4)`

**Comment by tvlieg** [comment] 2024-02-06 10:19
I have the same with "Noteshelf 3":
`-2131199389  Noteshelf 3                    (1.4.8)`

**Comment by jandamm** [comment] 2024-02-28 12:21
Same here for `StopTheMadness Pro` and `Keymapp`.

**Comment by deed02392** [comment] 2024-07-12 13:21
I think it's the other way around @jandamm – we want `Uint64` throughout Search:
https://github.com/mas-cli/mas/blob/main/Sources/MasKit/Controllers/MasStoreSearch.swift#L15

**Comment by rgoldberg** [comment] 2024-09-11 23:20
This is a duplicate of #478 (please follow that issue). PR #535 has been submitted to fix the issue.

If you think this issue is different than #478, please let us know.

**Closed by rgoldberg** 2024-09-11 23:20 UTC
Labels: 🐛 bug, ♊️ duplicate, 🖨 output
