### ISSUE TITLE
🐛 [BUG] Linuxbrew Error: undefined method `installed?' for OS::Mac::Xcode:Module

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#259] opened 2020-02-04 04:36 UTC
🆕 Installing: mas
Error: undefined method `installed?' for OS::Mac::Xcode:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting

add to formula
```
  depends_on :macos
```

**Comment by andrewcrook** [comment] 2020-11-12 12:06
Does this need to be raise with Homebrew's repository?

**Comment by phatblat** [comment] 2020-11-16 14:20
No, just something to configure on the formula to mark it as not compatible with Linuxbrew.

**Comment by chris-araman** [comment] 2021-04-27 05:18
Looks like this was resolved with https://github.com/mas-cli/mas/commit/7e3c03b43d3daf2e44664f343f77e1edaf5c58ab#diff-c28d89b8f0ee86b84e2ea6653986e5a5ae04a22d3a603936351d5ccdb275ef18R17.

@phatblat, can this be closed?

**Comment by chris-araman** [comment] 2021-04-27 05:50
It looks like this was resolved [here](https://github.com/mas-cli/mas/commit/7e3c03b43d3daf2e44664f343f77e1edaf5c58ab#diff-c28d89b8f0ee86b84e2ea6653986e5a5ae04a22d3a603936351d5ccdb275ef18R17).

@phatblat, can this be closed? If not, how do I reproduce this issue?

**Closed** 2021-07-05 20:50 UTC
Labels: 🐛 bug, 🗣 awaiting reporter reply
