### ISSUE TITLE
`signin` fails

### ISSUE THREAD

**Issue by GentleHoneyLover** [mas-cli/mas#147] opened 2018-06-19 14:11 UTC
Hello,

As of today mas signed out of App Store and cannot sign back in. Until a few hours ago, everything was working perfectly (I'm running mas upgrade two times per day via a script)

```console
$ mas upgrade
Upgrading 1 outdated application:
WhatsApp Desktop (0.2.9739)
Error: Not signed in

$ mas signin <my_email>
==> Signing in to Apple ID: <my_email>
Password: 
2018-06-19 16:13:39.166 mas[81026:6493032] -[__NSXPCInterfaceProxy_ISAccountService signInWithContext:replyBlock:]: unrecognized selector sent to instance 0x7fb5706015e0
2018-06-19 16:13:39.168 mas[81026:6493032] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSXPCInterfaceProxy_ISAccountService signInWithContext:replyBlock:]: unrecognized selector sent to instance 0x7fb5706015e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff5668832b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7d7f6c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff56720e04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff565fe870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff565fe238 _CF_forwarding_prep_0 + 120
	5   mas                                 0x00000001080eb462 _T0So14ISStoreAccountC3masE6signInABSSSg8username_AE8passwordSb12systemDialogtKFZTf4ggnd_n + 1026
	6   mas                                 0x0000000108108b80 _T03mas13SignInCommandV3runAA6ResultOyytAA8MASErrorOGAA0bC7OptionsVFTf4gXd_nTf4xnn_n + 592
	7   mas                                 0x00000001080d41f4 _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA06SignInB0VTg5Tf4gg_n + 340
	8   mas                                 0x00000001080c070d _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA04InfoB0VTG5TATm + 29
	9   mas                                 0x00000001080c05a0 _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA06SignInB0VTG5TA + 16
	10  mas                                 0x00000001080d2286 _T03mas15CommandRegistryC4mains5NeverOSaySSG9arguments_SS11defaultVerbyxc12errorHandlertFAA8MASErrorO_Tg508_T03mas8K42OIxx_ACIxi_TR011_T03masyAA8B5OcfU_Tf3npf_nTf1nncn_nTf4nxn_n + 518
	11  mas                                 0x00000001080bd7ff main + 5391
	12  libdyld.dylib                       0x00007fff7e410015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

Doing:

```console
$ mas signout
$ mas signin <my_email>
```

doesn't help either.

Bug? Any suggestions?

Running the latest macOS 10.13.5

Regards,
Pavel

**Comment by phatblat** [comment] 2018-06-20 18:11
Alas, this is a known issue in High Sierra (10.13) that has not been resolved yet. ☹️ 

Closing as a duplicate of #107

**Comment by phatblat** [comment] 2018-06-20 18:12
The only option right now is to sign into the Mac App Store GUI and then you can use other mas commands.

**Closed by phatblat** 2018-06-20 18:11 UTC
Labels: 🐛 bug, ♊️ duplicate
