### ISSUE TITLE
Redownload Unavailable with This Apple ID

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#86] opened 2017-04-19 22:15 UTC
I have had success in the past using mas. Just recently the warning above has popped up. I logged out of App Store and back in again. Could this be an issue with two step authorization?
I have never attempted to download the file that I know of, this is the first time.

![screen shot 2017-04-19 at 5 11 25 pm](https://cloud.githubusercontent.com/assets/9438406/25204554/9baa0f06-2523-11e7-9ee8-3b1646de998f.png)

**Comment by nuxnix** [comment] 2017-04-24 15:35
Duplicate of #85

**Closed** 2017-04-24 19:58 UTC
Labels: ♊️ duplicate, 🖨 output
