### ISSUE TITLE
`list` doesn't output iOS or iPadOS apps

### ISSUE THREAD

**Issue by nrlquaker** [mas-cli/mas#518] opened 2024-07-06 22:27 UTC
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 14.4.1 (23E224)

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

installed iOS apps are not included in mas list

## To Reproduce

1. Install iOS app to mac M1 via AppStore
1. run `mas list`
1. See that iOS app is not present

## Expected Behavior

installed iOS apps should be included in mas list

## Actual Behavior

installed iOS apps are not included in mas list

**Comment by tonyarnold** [comment] 2024-07-06 23:45
This issue is a duplicate of #321. Please subscribe to that issue for updates.

**Closed by tonyarnold** 2024-07-06 23:45 UTC
Labels: 🐛 bug, ♊️ duplicate, 🆕 feature request
