### ISSUE TITLE
🐛 [BUG] Seems that certain app IDs cannot be displayed.

### ISSUE THREAD

**Issue by properCase** [mas-cli/mas#534] opened 2024-09-08 21:37 UTC
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 15.1

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

> When I run `mas info snagit` the ID comes back as -2138780544 however, the actual ID is 6451154048. (https://apps.apple.com/us/app/techsmith-snagit-2024/id6451154048?mt=12)

It seems maybe a 32bit integer is being used, but the ID is greater than that?

## To Reproduce

1. mas search Snagit
2. Look at the ID.

## Expected Behavior

> A clear and concise description of what you expected to happen.

## Actual Behavior

> A clear and concise description of what actually happened.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```bash
$ mas search Snagit
...
```

**Comment by rgoldberg** [comment] 2024-09-11 23:19
This is a duplicate of #478 (please follow that issue). PR #535 has been submitted to fix the issue.

If you think this issue is different than #478, please let us know.

**Closed** 2024-09-11 23:20 UTC
Labels: 🐛 bug

**Comment by properCase** [comment] 2024-09-12 12:30
Thank you, @rgoldberg , I searched beforehand but whatever I searched for, didn't bring up either of those two!  I'll track it there!
