### ISSUE TITLE
`signin` crashes on Mojave

### ISSUE THREAD

**Issue by kevinji** [mas-cli/mas#170] opened 2018-09-25 02:52 UTC
I'm running into the following error when running `mas signin email@example.com`:
```
mas signin email@example.com
==> Signing in to Apple ID: email@example.com
Password:
2018-09-24 22:51:11.637 mas[4248:42068] -[__NSXPCInterfaceProxy_ISAccountService signInWithContext:replyBlock:]: unrecognized selector sent to instance 0x7fd53ee0e260
2018-09-24 22:51:11.640 mas[4248:42068] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSXPCInterfaceProxy_ISAccountService signInWithContext:replyBlock:]: unrecognized selector sent to instance 0x7fd53ee0e260'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4198743d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6d894720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff41a04255 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff41926ad0 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff41926478 _CF_forwarding_prep_0 + 120
	5   mas                                 0x000000010d0f1462 _T0So14ISStoreAccountC3masE6signInABSSSg8username_AE8passwordSb12systemDialogtKFZTf4ggnd_n + 1026
	6   mas                                 0x000000010d10eb80 _T03mas13SignInCommandV3runAA6ResultOyytAA8MASErrorOGAA0bC7OptionsVFTf4gXd_nTf4xnn_n + 592
	7   mas                                 0x000000010d0da1f4 _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA06SignInB0VTg5Tf4gg_n + 340
	8   mas                                 0x000000010d0c670d _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA04InfoB0VTG5TATm + 29
	9   mas                                 0x000000010d0c65a0 _T03mas14CommandWrapperVACyxGqd__c11ClientErrorQyd__RszAA0B8ProtocolRd__7Options_AEQYd__AFRSlu33_E513F8A29DAA43E418079999EEBED6A7LlfcAA6ResultOyytAA010CommandantE0OyxGGAA14ArgumentParserCcfU_AA8MASErrorO_AA06SignInB0VTG5TA + 16
	10  mas                                 0x000000010d0d8286 _T03mas15CommandRegistryC4mains5NeverOSaySSG9arguments_SS11defaultVerbyxc12errorHandlertFAA8MASErrorO_Tg508_T03mas8K42OIxx_ACIxi_TR011_T03masyAA8B5OcfU_Tf3npf_nTf1nncn_nTf4nxn_n + 518
	11  mas                                 0x000000010d0c37ff main + 5391
	12  libdyld.dylib                       0x00007fff6e962085 start + 1
	13  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    4248 abort      mas signin email@example.com
```

I'm assuming this is because of the new App Store redesign.

**Comment by mc10** [comment] 2018-09-25 04:40
Closing as dupe of #164.

**Closed** 2018-09-25 04:39 UTC
Labels: 🐛 bug
