### ISSUE TITLE
Downloading old application versions

### ISSUE THREAD

**Issue by Moosems** [mas-cli/mas#494] opened 2023-05-29 15:52 UTC
I run my Mac on 10.14.6 and am therefore unable to update or download many applications. On the App Store I am usually incapable of downloading older versions compatible with my Mac version. Is  there any way to achieve thiS?

**Comment by lalaRLH** [comment] 2024-03-02 07:37
I just saw this as I was browsing to see if there was a way to add a sunset app to a new Apple ID (i.e. users who installed old WhatsApp are still getting updates to it, despite it no longer showing in search for new users who don't have the app already). Anyways, what apps do you need? I've got access to an MDM and whenever the apps replaced, the tool just downloads the latest version - but leaves the older one there. We have stuff that goes back a long way. I could dig out if there's no alternate way, have you tried an alternate tool such as iMazing to see if that shows up an older version if you try and download the App on the 10.14 system (not sure if it will or not). https://imazing.com/blog/imazing-3-beta

**Comment by rgoldberg** [comment] 2024-09-13 10:49
Closing as a duplicate of #392. Please subscribe to / comment on that issue.

**Closed by rgoldberg** 2024-09-13 10:49 UTC
Labels: ♊️ duplicate, 🆕 feature request
