### ISSUE TITLE
`outdated` reports some current apps as outdated & duplicates some apps

### ISSUE THREAD

**Issue by BerndGoldschmidt** [mas-cli/mas#410] opened 2021-09-08 08:14 UTC
## Your Environment

- `mas version`: `1.8.2`
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`):
```
Software:

    System Software Overview:

      System Version: macOS 11.5.2 (20G95)
      Kernel Version: Darwin 20.6.0
      Time since boot: 9 days 9:55
```

### mas Install Method

- [X] `brew install mas` (homebrew-core)

## Describe the Bug

- mas reports apps as outdated even after upgrade
- mas reports the same apps multiple times

## To Reproduce

```
$ mas outdated     

Warning: Identifier 1094255754 not found in store. Was expected to identify Outbank.
Warning: Identifier 924726344 not found in store. Was expected to identify Deliveries.
1444383602 GoodNotes (5.7.26 -> 5.7.27)

$ mas upgrade

Upgrading 1 outdated application:
GoodNotes (5.7.26)
==> Downloading GoodNotes 5
==> Installed GoodNotes 5

$ mas outdated

Warning: Identifier 1094255754 not found in store. Was expected to identify Outbank.
Warning: Identifier 1094255754 not found in store. Was expected to identify Outbank.
Warning: Identifier 1094255754 not found in store. Was expected to identify Outbank.
Warning: Identifier 924726344 not found in store. Was expected to identify Deliveries.
Warning: Identifier 924726344 not found in store. Was expected to identify Deliveries.
1444383602 GoodNotes (5.7.26 -> 5.7.27)
1444383602 GoodNotes (5.7.26 -> 5.7.27)
```

## Expected Behavior

updated apps are no longer outdated

## Actual Behavior

same install is done over and over again

**Comment by chris-araman** [comment] 2021-09-08 18:22
> mas reports apps as outdated even after upgrade

This is because the `CFBundleShortVersionString` in the GoodNotes.app bundle is "5.7.26", but the version GoodNotes listed in the App Store is "5.7.27". We don't currently have a way to detect or resolve this condition. Pull requests welcome. Duplicate of #384.

> mas reports the same apps multiple times

This is likely because the app was found in multiple paths on your system. This issue would be addressed by d39058c7be405944fa1a172f39e5168fb9cef866, but that hasn't yet been included in a release. Dupe of #309.

**Closed by chris-araman** 2021-09-08 18:22 UTC
Labels: 🐛 bug, ♊️ duplicate
