### ISSUE TITLE
Is project abandoned?

### ISSUE THREAD

**Issue by XVilka** [mas-cli/mas#486] opened 2023-01-03 03:29 UTC
There are no commits for multiple months already and no reaction to the PRs or issues.

**Comment by ChrisChinchilla** [comment] 2023-02-15 09:42
I'd be interested in at least helping maintain if the current maintainers need help.

**Comment by natedunn** [comment] 2023-04-18 23:53
@XVilka If you look at the readme and the commits you can probably see the story pretty clearly:

Apple has been restricting API access with every new version of Mac OS. This means that there is less and less that the maintainers can do to keep these features running. That doesn't mean that its dead or doesn't have its uses... but you likely won't find many enhancements or new features do to theses issues.

If this project no longer meets your needs, I'd recommend looking into alternatives such as Homebrew's casks, if the applications you need are distributed that way.

**Comment by javadba** [comment] 2023-05-07 21:46
> @XVilka If you look at the readme and the commits you can probably see the story pretty clearly:
> 
> Apple has been restricting API access with every new version of Mac OS. This means that there is less and less that the maintainers can do to keep these features running. That doesn't mean that its dead or doesn't have its uses... but you likely won't find many enhancements or new features do to theses issues.
> 
> If this project no longer meets your needs, I'd recommend looking into alternatives such as Homebrew's casks, if the applications you need are distributed that way.

The apps of interest will not be in `homebrew` e.g. `Xcode`.  I'm trying to download Xcode in particular.

**Comment by rgoldberg** [comment] 2024-09-13 15:11
@phatblat has sporadically worked on betas for 1.8.7. I'm trying to help revive the project. Hopefully he & I will get in touch to map things out.

Closing this as a duplicate of #512. Please subscribe to that issue.

**Closed by rgoldberg** 2024-09-13 15:11 UTC
Labels: ♊️ duplicate, ❔ question
