### ISSUE TITLE
`signin` disabled on macOS 10.13+

### ISSUE THREAD

**Issue by dimag25** [mas-cli/mas#487] opened 2023-03-06 08:12 UTC
## Your Environment

- `mas version`: 1.8.6
- macOS version : 10.15 ( Catalina)

### mas Install Method
-  `brew install mas` (homebrew-core)

## Describe the Bug

my goal is create fully e2e automation with appium-mac-driver and to use this I must install `xcode` as prerequisite.

use case:

1. create mac mini vm instance in AWS
2. install xcode inside the mac vm

- flow runs from Jenkins
- macOS versions >= 10.15 (Catalina)

problems and errors:
I got blockers when I tried to install Xcode in automation flow .

found this article how to install : https://www.moncefbelyamani.com/how-to-install-xcode-with-homebrew/
problem : before use mas cli command to install xcode I must to signin to apple id ,
but `mas signin` command disabled on macOS 10.13+ : https://github.com/mas-cli/mas/issues/164

anyone have any idea how can I workaround this blocker? how can I install xcode from mac os terminal?

**Comment by shalins** [comment] 2023-03-07 23:48
having the same issue, need to be able to install xcode in a headless setup

**Comment by Dante1349** [comment] 2023-05-27 10:37
i also try to do this with ansible and a remote mac and i don't get any response from the command, but it seems that it was downloading, but then suddenly got stuck. I don't get a response in the shell that it is downloading, even when im on the mac via ssh.

**Comment by rgoldberg** [comment] 2024-09-05 10:16
Can we close this as a duplicate of #164?

**Comment by rgoldberg** [comment] 2024-09-11 23:35
Closing as a duplicate of #164 (please follow that issue).

If you think this issue is different than #164, please let us know.

**Closed by rgoldberg** 2024-09-11 23:35 UTC
Labels: 🐛 bug, ♊️ duplicate
